### ISSUE TITLE
Tracker: JavaDeck/SwiftDeck Mobile client libraries

### ISSUE THREAD

**Issue by ibgreen** [UnfoldedInc/unfolded.gl#6]
### Javascript (Playground Bundle)

- [ ] Unify and revisit the playground project that should be bundled with the app
- [ ] Mapbox token currently seems to be bundled during the build process, and setting the mapboxKey does not seem to have an effect
- [ ] Add a way to pipe the loading state to the end user so that they can handle initialization gracefully. This is currently the weakest point from UX standpoint, as we just end up with a white screen while the map/layers are being loaded
- [ ] Playground loads its own initial sample in the very start, we likely want to get rid of that as the user should be able to specify the initial state

### SwiftDeck:

- [ ] Add package manager support (Cocoapods, and perhaps SPM)
- [ ] Add an example for Mac. Perhaps make use of Catalyst?
- [ ] passing the frame buffer data.

### JavaDeck & SwiftDeck

- [ ] Revisit Deck/Layer/View mutability
- [ ] Add other map provider support?
- [ ] Align map API with [Scripting interface](https://deck.gl/#/documentation/deckgl-api-reference/scripting-interface/deckgl) where mapboxApiAccessToken is passed to Deck directly (playground requires View and specifying a map style within it instead of passing mapStyle to Deck) 

### Longer Term Ideas
- [ ] Full transport API implementation
- [ ] Separate out the transport implementation as an "independent module"
